# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 378b1c19ed69d87d496d5491cd69958792b5b740df6631de09b127809487811ccd273e1dec8d53ebced5bea82a6176646c76478299fe9f79c80cbcd41e496595

test:
  secret_key_base: d9174a00cd818dd42da9b69bea0ac0f302f359602a97284f28675bf7782aa878a1159aeb9554cbbec079f8c3a112286f3860cf9061b857ddd5f7e947d21552a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
